variable "rds_name" {}
variable "security_group_rds" {}
variable "vpc_id" {}
variable "master_password" {}
variable "master_username" {}
variable "database_name" {}
variable "subnet_group" {}
variable "private_subnet_id_rds1" {}
variable "private_subnet_id_rds2" {}