variable "rds_name" {}
variable "security_group_rds" {}
variable "vpc_id" {}
variable "master_password" {}
variable "master_username" {}
variable "database_name" {}
variable "subnet_group" {}
variable "private_subnet-a_id" {}
variable "private_subnet-c_id" {}