variable "function_name" {}
variable "CONTAINER_NAME" {}
variable "CRUD_FOR_ECS_SECRET_NAME" {}
variable "CRUSTER_NAME" {}
variable "SG_NAME" {}
variable "SUBNET_1" {}
variable "SUBNET_2" {}
variable "TASK_DEFINITION" {}
variable "subnet_lambda1" {}
variable "subnet_lambda2" {}
variable "security_group" {}
variable "role_name_lambda_exec" {}
variable "lambda_policy_name" {}